sudo: false

language: php

dist: trusty

php:
  - 7.0.13
  - 7.1

env:
  global:
    - VIPS_SITE=http://www.vips.ecs.soton.ac.uk/supported
    - VIPS_VERSION_MAJOR=8
    - VIPS_VERSION_MINOR=4
    - VIPS_VERSION_MICRO=4
    - VIPS_VERSION=$VIPS_VERSION_MAJOR.$VIPS_VERSION_MINOR
    - VIPS_VERSION_FULL=$VIPS_VERSION.$VIPS_VERSION_MICRO
    - PATH=$HOME/vips/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH
    - PYTHONPATH=$HOME/vips/lib/python2.7/site-packages:$PYTHONPATH
    - GI_TYPELIB_PATH=$HOME/vips/lib/girepository-1.0:$GI_TYPELIB_PATH

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/vips

addons:
  apt:
    packages:
      - gobject-introspection
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - libwebp-dev

before_install:
  - bash install-vips.sh
  - yes '' | pecl install vips

install: composer install --prefer-dist

script: composer test
